/* Generated by pnpm scenes:build. Edit art/brussels/places.json, conversations.json or pack.json, then rebuild. */
import { createPhase2CountryPack } from "./phase2-factory";

export const brusselsCountryPackV1 = createPhase2CountryPack({
  "packId": "brussels-v1",
  "countryCode": "BE",
  "countryName": "Belgium",
  "cityName": "Brussels",
  "timeZone": "Europe/Brussels",
  "lat": 50.8503,
  "lon": 4.3517,
  "neighbours": [
    "amsterdam-v1",
    "cologne-v1"
  ],
  "voteBlurb": "Galleries, squares and park paths across Brussels, ending with the Atomium.",
  "zones": [
    {
      "id": "brussels-arrival",
      "label": "Bruxelles-Central",
      "weather": "clear",
      "palette": [
        "#887777",
        "#bb9988",
        "#554444"
      ],
      "kind": "arrival",
      "tags": [
        "arrival",
        "station"
      ],
      "description": "First steps outside the central station on a broad paved street.",
      "stage": {
        "palette": [
          "#887777",
          "#bb9988",
          "#554444"
        ]
      }
    },
    {
      "id": "brussels-galeries",
      "label": "Galeries Royales Saint-Hubert",
      "weather": "clear",
      "palette": [
        "#222211",
        "#ccaa88",
        "#aa7744"
      ],
      "kind": "lanes",
      "tags": [
        "lanes",
        "gallery"
      ],
      "description": "A glass-roofed arcade stretches between warm stone shopfronts.",
      "stage": {
        "palette": [
          "#222211",
          "#ccaa88",
          "#aa7744"
        ]
      }
    },
    {
      "id": "brussels-grand-place",
      "label": "Grand-Place",
      "weather": "golden",
      "palette": [
        "#77aadd",
        "#665555",
        "#bbccee"
      ],
      "kind": "landmark",
      "tags": [
        "square",
        "landmark"
      ],
      "description": "The square opens between ornate guildhall facades and the city hall.",
      "stage": {
        "palette": [
          "#77aadd",
          "#665555",
          "#bbccee"
        ]
      }
    },
    {
      "id": "brussels-sainte-catherine",
      "label": "Place Sainte-Catherine",
      "weather": "breeze",
      "palette": [
        "#aaccff",
        "#887777",
        "#bb9988"
      ],
      "kind": "cafe",
      "tags": [
        "cafe",
        "square"
      ],
      "description": "A calm pedestrian square passes the church and empty café terraces.",
      "stage": {
        "palette": [
          "#aaccff",
          "#887777",
          "#bb9988"
        ]
      }
    },
    {
      "id": "brussels-marolles",
      "label": "The Marolles",
      "weather": "haze",
      "palette": [
        "#887777",
        "#111111",
        "#333333"
      ],
      "kind": "market",
      "tags": [
        "market",
        "lanes"
      ],
      "description": "A small cobbled street with modest shopfronts and market shutters.",
      "stage": {
        "palette": [
          "#887777",
          "#111111",
          "#333333"
        ]
      }
    },
    {
      "id": "brussels-sablon",
      "label": "Grand Sablon",
      "weather": "golden",
      "palette": [
        "#776666",
        "#998877",
        "#88bbff"
      ],
      "kind": "cafe",
      "tags": [
        "square",
        "cafe"
      ],
      "description": "Stone facades and church walls frame a broad cobbled square.",
      "stage": {
        "palette": [
          "#776666",
          "#998877",
          "#88bbff"
        ]
      }
    },
    {
      "id": "brussels-mont-des-arts",
      "label": "Mont des Arts",
      "weather": "clear",
      "palette": [
        "#88bbee",
        "#ffeecc",
        "#bbccee"
      ],
      "kind": "landmark",
      "tags": [
        "garden",
        "landmark"
      ],
      "description": "Formal garden paths look toward the centre of Brussels.",
      "stage": {
        "palette": [
          "#88bbee",
          "#ffeecc",
          "#bbccee"
        ]
      }
    },
    {
      "id": "brussels-park",
      "label": "Brussels Park",
      "weather": "breeze",
      "palette": [
        "#bbccee",
        "#886655",
        "#ffcc99"
      ],
      "kind": "lanes",
      "tags": [
        "garden",
        "lanes"
      ],
      "description": "Tree-lined walks and lawns sit beside the Royal Quarter.",
      "stage": {
        "palette": [
          "#bbccee",
          "#886655",
          "#ffcc99"
        ]
      }
    },
    {
      "id": "brussels-cinquantenaire",
      "label": "Parc du Cinquantenaire",
      "weather": "clear",
      "palette": [
        "#887777",
        "#ffddaa",
        "#99bbdd"
      ],
      "kind": "landmark",
      "tags": [
        "garden",
        "landmark"
      ],
      "description": "The park path leads toward the triumphal arch and colonnades.",
      "stage": {
        "palette": [
          "#887777",
          "#ffddaa",
          "#99bbdd"
        ]
      }
    },
    {
      "id": "brussels-atomium",
      "label": "Atomium viewpoint",
      "weather": "evening",
      "palette": [
        "#7799cc",
        "#997777",
        "#ffbb88"
      ],
      "kind": "landmark",
      "tags": [
        "landmark",
        "evening"
      ],
      "description": "The Atomium rises above the open path as the light softens.",
      "stage": {
        "palette": [
          "#7799cc",
          "#997777",
          "#ffbb88"
        ]
      }
    }
  ],
  "sceneVisitSeconds": 420,
  "encounter": {
    "npcId": "brussels-resident",
    "locationLabel": "Galeries Royales Saint-Hubert",
    "phrase": {
      "original": "Bonjour, je découvre Bruxelles à pied.",
      "transliteration": "Bon-zhoor, zhuh day-koovr Bruh-sel ah pyay.",
      "gloss": "Hello, I am discovering Brussels on foot.",
      "pronunciation": "bon-ZHOOR, zhuh day-KOOVR bruh-SEL ah PYAY"
    },
    "exchange": [
      "Bonjour. Did you find your way from the station?",
      "Yes. The streets are opening up ahead.",
      "The galleries and the Grand-Place are close to the centre.",
      "I would like to see both on foot.",
      "There is room to pause in the parks too.",
      "Then I will take the day one place at a time."
    ],
    "dialogue": [
      {
        "speaker": "npc",
        "text": "Bonjour. Did you find your way from the station?",
        "mood": "curious"
      },
      {
        "speaker": "traveler",
        "text": "Yes. The streets are opening up ahead.",
        "mood": "neutral"
      },
      {
        "speaker": "npc",
        "text": "The galleries and the Grand-Place are close to the centre.",
        "mood": "neutral"
      },
      {
        "speaker": "traveler",
        "text": "I would like to see both on foot.",
        "mood": "thoughtful"
      },
      {
        "speaker": "npc",
        "text": "There is room to pause in the parks too.",
        "mood": "neutral"
      },
      {
        "speaker": "traveler",
        "text": "Then I will take the day one place at a time.",
        "mood": "amused"
      }
    ]
  },
  "conversations": [],
  "resident": {
    "name": "Visitor",
    "role": "Virtual route companion",
    "variantId": "resident-a"
  },
  "notebookLines": [
    "The walk began outside Bruxelles-Central.",
    "The covered gallery held a quieter kind of city light.",
    "Grand-Place opened into a broad square of detailed facades.",
    "At Sainte-Catherine, the route slowed beside empty terraces.",
    "The Marolles lane felt smaller after the big square.",
    "Sablon brought stone facades and another open place to cross.",
    "Mont des Arts made a pause before the long park paths.",
    "The Atomium marked the last view of the day."
  ],
  "postcardTitle": "A day across Brussels",
  "postcardCopy": "Ten places later, the route reached the Atomium in the evening light.",
  "postcardBackgroundUrl": "/scenes/brussels/v1/postcard.webp",
  "sourceNotes": [
    "Scene manifest v1 for Brussels: 10 places; cultural-safety review is still required.",
    "AI-assisted source paintings and runtime renditions are hosted under scenes/brussels/v1/ on the asset origin; the repository keeps only the manifest and authoring text."
  ],
  "culturalReview": {
    "reviewerName": null,
    "reviewedAt": null,
    "status": "pending",
    "qualification": null,
    "disposition": null,
    "publicLaunchRequirement": null,
    "citations": [],
    "notes": "Generated scene manifest awaiting the owner's documented cultural-safety review."
  },
  "assetBudgetBytes": 5767168,
  "authoredAssets": {
    "variants": {
      "brussels-arrival": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/city-full-1920.36ebbea250.webp",
            "width": 1920,
            "height": 640,
            "bytes": 239192,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/city-full-2560.6051566d5b.webp",
            "width": 2560,
            "height": 853,
            "bytes": 341636,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/city-full-3600.840df6ef74.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 499762,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/city-center-800.3485105088.webp",
            "width": 800,
            "height": 800,
            "bytes": 90218,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/city-center-1200.cc2c163cfb.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 143124,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/sky-full-800.36c65ad9c5.webp",
            "width": 800,
            "height": 450,
            "bytes": 46256,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/sky-full-1600.5b8f6c980e.webp",
            "width": 1600,
            "height": 900,
            "bytes": 97790,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/ground-full-1800.921ee1bd20.webp",
            "width": 1800,
            "height": 108,
            "bytes": 26106,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-arrival/ground-full-3600.6a3a5aa420.webp",
            "width": 3600,
            "height": 216,
            "bytes": 61684,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-galeries": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/city-full-1920.ec6b0f552a.webp",
            "width": 1920,
            "height": 640,
            "bytes": 264330,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/city-full-2560.795016b0f3.webp",
            "width": 2560,
            "height": 853,
            "bytes": 371098,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/city-full-3600.3b107a0caf.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 546078,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/city-center-800.335d7ac4c6.webp",
            "width": 800,
            "height": 800,
            "bytes": 123676,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/city-center-1200.6f2a479450.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 194368,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/sky-full-800.813899d656.webp",
            "width": 800,
            "height": 450,
            "bytes": 44522,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/sky-full-1600.ce341f56a3.webp",
            "width": 1600,
            "height": 900,
            "bytes": 94624,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/ground-full-1800.1d34b4264f.webp",
            "width": 1800,
            "height": 108,
            "bytes": 33778,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-galeries/ground-full-3600.8e99514889.webp",
            "width": 3600,
            "height": 216,
            "bytes": 75764,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-grand-place": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/city-full-1920.e56423824d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 282588,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/city-full-2560.515b14572b.webp",
            "width": 2560,
            "height": 853,
            "bytes": 402416,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/city-full-3600.2a9f4c779c.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 582436,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/city-center-800.9691ce22b0.webp",
            "width": 800,
            "height": 800,
            "bytes": 91948,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/city-center-1200.d24ca8f50d.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 144826,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/sky-full-800.63e25eb96b.webp",
            "width": 800,
            "height": 450,
            "bytes": 45516,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/sky-full-1600.44b6c072ad.webp",
            "width": 1600,
            "height": 900,
            "bytes": 95318,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/ground-full-1800.6b3ff297d0.webp",
            "width": 1800,
            "height": 108,
            "bytes": 38604,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-grand-place/ground-full-3600.3fd0ab6ff8.webp",
            "width": 3600,
            "height": 216,
            "bytes": 89134,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-sainte-catherine": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/city-full-1920.fc5bd48a3a.webp",
            "width": 1920,
            "height": 640,
            "bytes": 296620,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/city-full-2560.e21d18abf6.webp",
            "width": 2560,
            "height": 853,
            "bytes": 421116,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/city-full-3600.6fa2562cdf.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 606426,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/city-center-800.1a1b6cb6a7.webp",
            "width": 800,
            "height": 800,
            "bytes": 106696,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/city-center-1200.0c47662b9d.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 166294,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/sky-full-800.90c8c3e8bb.webp",
            "width": 800,
            "height": 450,
            "bytes": 55660,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/sky-full-1600.8d6ae922fd.webp",
            "width": 1600,
            "height": 900,
            "bytes": 117100,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/ground-full-1800.3fc775186e.webp",
            "width": 1800,
            "height": 108,
            "bytes": 31950,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sainte-catherine/ground-full-3600.f2ac65a870.webp",
            "width": 3600,
            "height": 216,
            "bytes": 69342,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-marolles": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/city-full-1920.0bf7f210a9.webp",
            "width": 1920,
            "height": 640,
            "bytes": 332286,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/city-full-2560.ce96fa958e.webp",
            "width": 2560,
            "height": 853,
            "bytes": 469186,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/city-full-3600.13100630e5.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 691762,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/city-center-800.d48a989e6c.webp",
            "width": 800,
            "height": 800,
            "bytes": 154996,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/city-center-1200.03bd3f8009.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 244524,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/sky-full-800.58ac09356c.webp",
            "width": 800,
            "height": 450,
            "bytes": 57918,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/sky-full-1600.a30549d874.webp",
            "width": 1600,
            "height": 900,
            "bytes": 123896,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/ground-full-1800.e06390f1a7.webp",
            "width": 1800,
            "height": 108,
            "bytes": 44918,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-marolles/ground-full-3600.d3dd169da1.webp",
            "width": 3600,
            "height": 216,
            "bytes": 97712,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-sablon": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/city-full-1920.765d9cdff6.webp",
            "width": 1920,
            "height": 640,
            "bytes": 335088,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/city-full-2560.76fc08bc66.webp",
            "width": 2560,
            "height": 853,
            "bytes": 479528,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/city-full-3600.452456570b.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 708212,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/city-center-800.97aef4aab7.webp",
            "width": 800,
            "height": 800,
            "bytes": 141080,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/city-center-1200.eec8bf0a83.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 223874,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/sky-full-800.2b8347d1c1.webp",
            "width": 800,
            "height": 450,
            "bytes": 59170,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/sky-full-1600.4a0bcb4522.webp",
            "width": 1600,
            "height": 900,
            "bytes": 123488,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/ground-full-1800.909484e111.webp",
            "width": 1800,
            "height": 108,
            "bytes": 39468,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-sablon/ground-full-3600.0d1bd585cf.webp",
            "width": 3600,
            "height": 216,
            "bytes": 88274,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-mont-des-arts": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/city-full-1920.071065e57d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 230908,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/city-full-2560.9cb0ed8407.webp",
            "width": 2560,
            "height": 853,
            "bytes": 328808,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/city-full-3600.8d8f49a52a.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 485030,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/city-center-800.b22cc15152.webp",
            "width": 800,
            "height": 800,
            "bytes": 90286,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/city-center-1200.3070a09805.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 145772,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/sky-full-800.9e69944383.webp",
            "width": 800,
            "height": 450,
            "bytes": 44836,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/sky-full-1600.647a4df06d.webp",
            "width": 1600,
            "height": 900,
            "bytes": 98352,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/ground-full-1800.6d7e2763dc.webp",
            "width": 1800,
            "height": 108,
            "bytes": 19244,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-mont-des-arts/ground-full-3600.ab4881f24b.webp",
            "width": 3600,
            "height": 216,
            "bytes": 45200,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-park": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-park/city-full-1920.64eb972f9a.webp",
            "width": 1920,
            "height": 640,
            "bytes": 321790,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/city-full-2560.dce7c7361a.webp",
            "width": 2560,
            "height": 853,
            "bytes": 467500,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/city-full-3600.5cf0ba6afb.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 691666,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/city-center-800.3016e0686d.webp",
            "width": 800,
            "height": 800,
            "bytes": 102170,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/city-center-1200.b738577b61.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 166042,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-park/sky-full-800.528519793f.webp",
            "width": 800,
            "height": 450,
            "bytes": 61656,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/sky-full-1600.dbf1e38b78.webp",
            "width": 1600,
            "height": 900,
            "bytes": 133682,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-park/ground-full-1800.e73b3a78a2.webp",
            "width": 1800,
            "height": 108,
            "bytes": 36968,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-park/ground-full-3600.cf1ebf7b1e.webp",
            "width": 3600,
            "height": 216,
            "bytes": 83068,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-cinquantenaire": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/city-full-1920.8c0af22fd7.webp",
            "width": 1920,
            "height": 640,
            "bytes": 261234,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/city-full-2560.ed6435a7f1.webp",
            "width": 2560,
            "height": 853,
            "bytes": 372938,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/city-full-3600.ea827019b9.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 548614,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/city-center-800.519b74a603.webp",
            "width": 800,
            "height": 800,
            "bytes": 83096,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/city-center-1200.895c37c773.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 131886,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/sky-full-800.6c9ec58140.webp",
            "width": 800,
            "height": 450,
            "bytes": 45940,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/sky-full-1600.e21313475e.webp",
            "width": 1600,
            "height": 900,
            "bytes": 100328,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/ground-full-1800.8e9b18e927.webp",
            "width": 1800,
            "height": 108,
            "bytes": 34394,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-cinquantenaire/ground-full-3600.75506fce9a.webp",
            "width": 3600,
            "height": 216,
            "bytes": 79420,
            "crop": "full"
          }
        ],
        "night": []
      },
      "brussels-atomium": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/city-full-1920.31cedac130.webp",
            "width": 1920,
            "height": 640,
            "bytes": 273964,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/city-full-2560.3466c12af1.webp",
            "width": 2560,
            "height": 853,
            "bytes": 392550,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/city-full-3600.c94f43ff9b.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 586216,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/city-center-800.9d760bd5ab.webp",
            "width": 800,
            "height": 800,
            "bytes": 99082,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/city-center-1200.ca807126c3.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 158990,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/sky-full-800.3a3bca0f06.webp",
            "width": 800,
            "height": 450,
            "bytes": 44494,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/sky-full-1600.31202dd422.webp",
            "width": 1600,
            "height": 900,
            "bytes": 97728,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/ground-full-1800.9715e5c0b1.webp",
            "width": 1800,
            "height": 108,
            "bytes": 29500,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/ground-full-3600.af5fe645f5.webp",
            "width": 3600,
            "height": 216,
            "bytes": 70216,
            "crop": "full"
          }
        ],
        "night": [
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/night-full-1920.d38ab0ec35.webp",
            "width": 1920,
            "height": 640,
            "bytes": 212706,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/night-full-2560.df23d765a2.webp",
            "width": 2560,
            "height": 853,
            "bytes": 303644,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/night-full-3600.612a117566.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 442708,
            "crop": "full"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/night-center-800.7a98e352ca.webp",
            "width": 800,
            "height": 800,
            "bytes": 85396,
            "crop": "center"
          },
          {
            "url": "/scenes/brussels/v1/places/brussels-atomium/night-center-1200.816c9e23cb.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 133502,
            "crop": "center"
          }
        ]
      }
    }
  }
});
