/* Generated by pnpm pack:new / pack:build. Edit art/paris/pack.json, then rebuild. */
import { createPhase2CountryPack } from "./phase2-factory";

export const parisCountryPackV1 = createPhase2CountryPack({
  "packId": "paris-v1",
  "countryCode": "FR",
  "countryName": "France",
  "cityName": "Paris",
  "timeZone": "Europe/Paris",
  "lat": 48.8566,
  "lon": 2.3522,
  "neighbours": [],
  "voteBlurb": "Station boulevards, canal paths, market passages and the Seine, ending beneath the evening lights.",
  "zones": [
    {
      "id": "paris-arrival",
      "label": "Paris arrival",
      "weather": "clear",
      "palette": [
        "#aaccee",
        "#aa9988",
        "#777777"
      ],
      "stage": {
        "palette": [
          "#aaccee",
          "#aa9988",
          "#777777"
        ]
      }
    },
    {
      "id": "paris-lanes",
      "label": "Paris neighbourhood lanes",
      "weather": "breeze",
      "palette": [
        "#888888",
        "#ccaa99",
        "#aaccee"
      ],
      "stage": {
        "palette": [
          "#888888",
          "#ccaa99",
          "#aaccee"
        ]
      }
    },
    {
      "id": "paris-market",
      "label": "Paris market",
      "weather": "haze",
      "palette": [
        "#888888",
        "#eeccaa",
        "#ccaa99"
      ],
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#ccaa99"
        ]
      }
    },
    {
      "id": "paris-cafe",
      "label": "Paris cafe",
      "weather": "golden",
      "palette": [
        "#888888",
        "#eeccaa",
        "#663333"
      ],
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#663333"
        ]
      }
    },
    {
      "id": "paris-landmark",
      "label": "The Seine and Eiffel Tower",
      "weather": "evening",
      "palette": [
        "#776666",
        "#8899cc",
        "#ffbb77"
      ],
      "stage": {
        "palette": [
          "#776666",
          "#8899cc",
          "#ffbb77"
        ]
      }
    }
  ],
  "encounter": {
    "npcId": "paris-resident",
    "locationLabel": "Paris neighbourhood lanes",
    "phrase": {
      "original": "Bonjour, je découvre Paris à pied.",
      "transliteration": "Bon-zhoor, zhuh day-koovr Pa-ree ah pyay.",
      "gloss": "Hello, I am discovering Paris on foot.",
      "pronunciation": "bon-ZHOOR, zhuh day-KOOVR pah-REE ah PYAY"
    },
    "exchange": [
      "Bonjour! Are you finding your way from the station?",
      "Bonjour. Yes, I am discovering Paris on foot.",
      "Follow the canal for a quieter start; the city changes pace beside the water.",
      "That sounds better than rushing straight to the famous view.",
      "There is time for the market, a café, and the river before evening.",
      "Merci, Camille. I will let the streets lead me there."
    ],
    "dialogue": [
      {
        "speaker": "npc",
        "text": "Bonjour! Are you finding your way from the station?",
        "mood": "curious"
      },
      {
        "speaker": "traveler",
        "text": "Bonjour. Yes, I am discovering Paris on foot.",
        "mood": "amused"
      },
      {
        "speaker": "npc",
        "text": "Follow the canal for a quieter start; the city changes pace beside the water.",
        "mood": "thoughtful"
      },
      {
        "speaker": "traveler",
        "text": "That sounds better than rushing straight to the famous view.",
        "mood": "thoughtful"
      },
      {
        "speaker": "npc",
        "text": "There is time for the market, a café, and the river before evening.",
        "mood": "neutral"
      },
      {
        "speaker": "traveler",
        "text": "Merci, Camille. I will let the streets lead me there.",
        "mood": "amused"
      }
    ]
  },
  "resident": {
    "name": "Camille",
    "role": "Canal-side resident",
    "variantId": "paris-resident-b"
  },
  "notebookLines": [
    "The station opened onto pale stone and a long morning pavement.",
    "Canal water made the city feel quieter without making it still.",
    "An iron footbridge held the middle of the view for a few steps.",
    "The market lane traded grand facades for flowers, produce and small doors.",
    "Lunch arrived as a pause at the edge of a Left Bank side street.",
    "The best parts of the route were the changes in scale between each district.",
    "The Seine widened the horizon just as the light began to soften.",
    "At night, the same riverside view felt newly drawn in blue and gold."
  ],
  "postcardTitle": "Evening beside the Seine",
  "postcardCopy": "Five Paris streets later, the river opened and the tower caught the last light.",
  "sourceNotes": [
    "P19 authoring record for Paris; cultural-safety review is still required.",
    "AI-assisted source paintings are preserved under art/paris; the build pipeline only derives runtime assets and makes no cultural claims."
  ],
  "culturalReview": {
    "reviewerName": null,
    "reviewedAt": null,
    "status": "pending",
    "qualification": null,
    "disposition": null,
    "publicLaunchRequirement": null,
    "citations": [],
    "notes": "Generated pack awaiting the owner's documented cultural-safety review."
  },
  "assetBudgetBytes": 5767168,
  "authoredAssets": {
    "nightZoneIds": [
      "paris-landmark"
    ],
    "lightsZoneIds": [],
    "continuousSceneZoneIds": [
      "paris-arrival",
      "paris-lanes",
      "paris-market",
      "paris-cafe",
      "paris-landmark"
    ]
  }
});
