/* Generated by pnpm scenes:build. Edit art/paris/places.json, conversations.json or pack.json, then rebuild. */
import { createPhase2CountryPack } from "./phase2-factory";

export const parisCountryPackV2 = createPhase2CountryPack({
  "packId": "paris-v2",
  "countryCode": "FR",
  "countryName": "France",
  "cityName": "Paris",
  "timeZone": "Europe/Paris",
  "lat": 48.8566,
  "lon": 2.3522,
  "neighbours": [],
  "voteBlurb": "Station boulevards, canal paths, market passages and the Seine, ending beneath the evening lights.",
  "zones": [
    {
      "id": "paris-arrival",
      "label": "Gare du Nord",
      "weather": "clear",
      "palette": [
        "#aaccee",
        "#aa9988",
        "#777777"
      ],
      "kind": "arrival",
      "tags": [
        "arrival",
        "station"
      ],
      "description": "First steps outside the station, on pale stone and a long morning pavement.",
      "stage": {
        "palette": [
          "#aaccee",
          "#aa9988",
          "#777777"
        ]
      }
    },
    {
      "id": "paris-lanes",
      "label": "Canal Saint-Martin",
      "weather": "breeze",
      "palette": [
        "#888888",
        "#ccaa99",
        "#aaccee"
      ],
      "kind": "lanes",
      "tags": [
        "lanes",
        "canal"
      ],
      "description": "A quiet canal promenade under plane trees, with an iron footbridge.",
      "stage": {
        "palette": [
          "#888888",
          "#ccaa99",
          "#aaccee"
        ]
      }
    },
    {
      "id": "paris-market",
      "label": "Marais market street",
      "weather": "haze",
      "palette": [
        "#888888",
        "#eeccaa",
        "#ccaa99"
      ],
      "kind": "market",
      "tags": [
        "market"
      ],
      "description": "Covered stalls, flowers and small doors in the Marais.",
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#ccaa99"
        ]
      }
    },
    {
      "id": "paris-cafe",
      "label": "Left Bank café",
      "weather": "golden",
      "palette": [
        "#888888",
        "#eeccaa",
        "#663333"
      ],
      "kind": "cafe",
      "tags": [
        "cafe"
      ],
      "description": "A calm corner café with empty tables on a Left Bank side street.",
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#663333"
        ]
      }
    },
    {
      "id": "paris-landmark",
      "label": "The Seine and the Eiffel Tower",
      "weather": "evening",
      "palette": [
        "#776666",
        "#8899cc",
        "#ffbb77"
      ],
      "kind": "landmark",
      "tags": [
        "landmark",
        "river"
      ],
      "description": "The river widens and the tower comes into view as the light softens.",
      "stage": {
        "palette": [
          "#776666",
          "#8899cc",
          "#ffbb77"
        ]
      }
    }
  ],
  "sceneVisitSeconds": 420,
  "encounter": {
    "npcId": "paris-resident",
    "locationLabel": "Canal Saint-Martin",
    "phrase": {
      "original": "Bonjour, je découvre Paris à pied.",
      "transliteration": "Bon-zhoor, zhuh day-koovr Pa-ree ah pyay.",
      "gloss": "Hello, I am discovering Paris on foot.",
      "pronunciation": "bon-ZHOOR, zhuh day-KOOVR pah-REE ah PYAY"
    },
    "exchange": [
      "Bonjour! Are you finding your way from the station?",
      "Bonjour. Yes, I am discovering Paris on foot.",
      "Follow the canal for a quieter start; the city changes pace beside the water.",
      "That sounds better than rushing straight to the famous view.",
      "There is time for the market, a café, and the river before evening.",
      "Merci, Camille. I will let the streets lead me there."
    ],
    "dialogue": [
      {
        "speaker": "npc",
        "text": "Bonjour! Are you finding your way from the station?",
        "mood": "curious"
      },
      {
        "speaker": "traveler",
        "text": "Bonjour. Yes, I am discovering Paris on foot.",
        "mood": "amused"
      },
      {
        "speaker": "npc",
        "text": "Follow the canal for a quieter start; the city changes pace beside the water.",
        "mood": "thoughtful"
      },
      {
        "speaker": "traveler",
        "text": "That sounds better than rushing straight to the famous view.",
        "mood": "thoughtful"
      },
      {
        "speaker": "npc",
        "text": "There is time for the market, a café, and the river before evening.",
        "mood": "neutral"
      },
      {
        "speaker": "traveler",
        "text": "Merci, Camille. I will let the streets lead me there.",
        "mood": "amused"
      }
    ]
  },
  "conversations": [
    {
      "id": "paris-welcome",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "lanes"
      ],
      "role": "story",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Are you finding your way from the station?",
          "mood": "curious"
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Yes, I am discovering Paris on foot.",
          "mood": "amused"
        },
        {
          "speaker": "npc",
          "text": "Follow the canal for a quieter start; the city changes pace beside the water.",
          "mood": "thoughtful"
        },
        {
          "speaker": "traveler",
          "text": "That sounds better than rushing straight to the famous view.",
          "mood": "thoughtful"
        },
        {
          "speaker": "npc",
          "text": "There is time for the market, a café, and the river before evening.",
          "mood": "neutral"
        },
        {
          "speaker": "traveler",
          "text": "Merci, Camille. I will let the streets lead me there.",
          "mood": "amused"
        }
      ]
    },
    {
      "id": "paris-station-hello",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "arrival",
        "station"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Are you finding your way from the station?",
          "mood": "curious"
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Yes, I am discovering Paris on foot.",
          "mood": "amused"
        }
      ]
    },
    {
      "id": "paris-canal-advice",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "arrival",
        "lanes",
        "canal"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Follow the canal for a quieter start; the city changes pace beside the water.",
          "mood": "thoughtful"
        },
        {
          "speaker": "traveler",
          "text": "That sounds better than rushing straight to the famous view.",
          "mood": "thoughtful"
        }
      ]
    },
    {
      "id": "paris-before-evening",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "lanes",
        "market",
        "cafe"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "There is time for the market, a café, and the river before evening.",
          "mood": "neutral"
        },
        {
          "speaker": "traveler",
          "text": "Merci, Camille. I will let the streets lead me there.",
          "mood": "amused"
        }
      ]
    },
    {
      "id": "paris-market-peaches",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "market"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Take a look at the peaches before they sell out.",
          "mood": "curious"
        },
        {
          "speaker": "traveler",
          "text": "They smell like the end of summer. Merci!",
          "mood": "amused"
        }
      ]
    },
    {
      "id": "paris-cafe-minute",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "cafe"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Nobody rushes a coffee here. Sit for a minute if you can.",
          "mood": "neutral"
        },
        {
          "speaker": "traveler",
          "text": "A minute is exactly what my feet wanted.",
          "mood": "amused"
        }
      ]
    },
    {
      "id": "paris-footbridge-view",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "lanes",
        "canal"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "Stop halfway across the footbridge. The water looks best from the middle.",
          "mood": "thoughtful"
        },
        {
          "speaker": "traveler",
          "text": "Then I will stop halfway. Thank you.",
          "mood": "neutral"
        }
      ]
    },
    {
      "id": "paris-quay-bookstalls",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "river",
        "landmark"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "The green bookstalls along the quay are worth a slow look.",
          "mood": "curious"
        },
        {
          "speaker": "traveler",
          "text": "Then I will walk slowly and look twice.",
          "mood": "thoughtful"
        }
      ]
    },
    {
      "id": "paris-tower-lights",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "landmark"
      ],
      "role": "ambient",
      "review": "pending",
      "lines": [
        {
          "speaker": "npc",
          "text": "After dark the tower sparkles for a few minutes every hour.",
          "mood": "surprised"
        },
        {
          "speaker": "traveler",
          "text": "Then I have a good reason to come back tonight.",
          "mood": "amused"
        }
      ]
    }
  ],
  "resident": {
    "name": "Camille",
    "role": "Canal-side resident",
    "variantId": "paris-resident-b"
  },
  "notebookLines": [
    "The station opened onto pale stone and a long morning pavement.",
    "Canal water made the city feel quieter without making it still.",
    "An iron footbridge held the middle of the view for a few steps.",
    "The market lane traded grand facades for flowers, produce and small doors.",
    "Lunch arrived as a pause at the edge of a Left Bank side street.",
    "The best parts of the route were the changes in scale between each district.",
    "The Seine widened the horizon just as the light began to soften.",
    "At night, the same riverside view felt newly drawn in blue and gold."
  ],
  "postcardTitle": "Evening beside the Seine",
  "postcardCopy": "Five Paris streets later, the river opened and the tower caught the last light.",
  "sourceNotes": [
    "Scene manifest v2 for Paris: 5 places; cultural-safety review is still required.",
    "AI-assisted source paintings are preserved under art/paris; the build derives content-addressed renditions and makes no cultural claims."
  ],
  "culturalReview": {
    "reviewerName": null,
    "reviewedAt": null,
    "status": "pending",
    "qualification": null,
    "disposition": null,
    "publicLaunchRequirement": null,
    "citations": [],
    "notes": "Generated scene manifest awaiting the owner's documented cultural-safety review."
  },
  "assetBudgetBytes": 5767168,
  "authoredAssets": {
    "variants": {
      "paris-arrival": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v2/places/paris-arrival/city-full-1920.fe745ffe8d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 242670,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/city-full-2560.f369ba3fd8.webp",
            "width": 2560,
            "height": 853,
            "bytes": 341488,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/city-full-3600.609a458a53.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 506652,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/city-center-800.1b08210e6b.webp",
            "width": 800,
            "height": 800,
            "bytes": 79194,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/city-center-1200.c482f39da5.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 124290,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v2/places/paris-arrival/sky-full-800.6ac25de359.webp",
            "width": 800,
            "height": 450,
            "bytes": 42760,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/sky-full-1600.53c0a6baa7.webp",
            "width": 1600,
            "height": 900,
            "bytes": 93618,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v2/places/paris-arrival/ground-full-1800.e6aab87308.webp",
            "width": 1800,
            "height": 108,
            "bytes": 18382,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-arrival/ground-full-3600.c17dc5c232.webp",
            "width": 3600,
            "height": 216,
            "bytes": 42084,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-lanes": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v2/places/paris-lanes/city-full-1920.0112f7c653.webp",
            "width": 1920,
            "height": 640,
            "bytes": 287166,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/city-full-2560.6e4f2f6580.webp",
            "width": 2560,
            "height": 853,
            "bytes": 399690,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/city-full-3600.c5ba29a782.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 580176,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/city-center-800.9429832f5e.webp",
            "width": 800,
            "height": 800,
            "bytes": 111486,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/city-center-1200.eb178309d3.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 174052,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v2/places/paris-lanes/sky-full-800.29c28f1089.webp",
            "width": 800,
            "height": 450,
            "bytes": 57580,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/sky-full-1600.6c5740fae6.webp",
            "width": 1600,
            "height": 900,
            "bytes": 125314,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v2/places/paris-lanes/ground-full-1800.1eb210d23d.webp",
            "width": 1800,
            "height": 108,
            "bytes": 17786,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-lanes/ground-full-3600.b27c1833f4.webp",
            "width": 3600,
            "height": 216,
            "bytes": 40000,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-market": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v2/places/paris-market/city-full-1920.27276a734d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 290890,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/city-full-2560.16c4ca7e41.webp",
            "width": 2560,
            "height": 853,
            "bytes": 416726,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/city-full-3600.8909e99a60.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 604960,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/city-center-800.b98dede687.webp",
            "width": 800,
            "height": 800,
            "bytes": 127542,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/city-center-1200.15c0aef7f1.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 201712,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v2/places/paris-market/sky-full-800.8eef0ba4d1.webp",
            "width": 800,
            "height": 450,
            "bytes": 60450,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/sky-full-1600.5480b242c4.webp",
            "width": 1600,
            "height": 900,
            "bytes": 127356,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v2/places/paris-market/ground-full-1800.20197c79d0.webp",
            "width": 1800,
            "height": 108,
            "bytes": 19458,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-market/ground-full-3600.f83820bd71.webp",
            "width": 3600,
            "height": 216,
            "bytes": 44836,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-cafe": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v2/places/paris-cafe/city-full-1920.68ce8e0949.webp",
            "width": 1920,
            "height": 640,
            "bytes": 295342,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/city-full-2560.b769c0290a.webp",
            "width": 2560,
            "height": 853,
            "bytes": 412050,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/city-full-3600.cc6b2b4101.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 609418,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/city-center-800.52cdf0641d.webp",
            "width": 800,
            "height": 800,
            "bytes": 104930,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/city-center-1200.a1c15a5d01.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 163394,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v2/places/paris-cafe/sky-full-800.8983ff8aa5.webp",
            "width": 800,
            "height": 450,
            "bytes": 61752,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/sky-full-1600.e8df8a8779.webp",
            "width": 1600,
            "height": 900,
            "bytes": 129976,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v2/places/paris-cafe/ground-full-1800.e968719bb5.webp",
            "width": 1800,
            "height": 108,
            "bytes": 22120,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-cafe/ground-full-3600.01bb792370.webp",
            "width": 3600,
            "height": 216,
            "bytes": 49596,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-landmark": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v2/places/paris-landmark/city-full-1920.374e149d23.webp",
            "width": 1920,
            "height": 640,
            "bytes": 250962,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/city-full-2560.12d0682b43.webp",
            "width": 2560,
            "height": 853,
            "bytes": 349196,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/city-full-3600.1b5d0ad2b0.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 511890,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/city-center-800.4806bb150a.webp",
            "width": 800,
            "height": 800,
            "bytes": 80118,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/city-center-1200.ffeef9750e.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 127282,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v2/places/paris-landmark/sky-full-800.6aabb7ee79.webp",
            "width": 800,
            "height": 450,
            "bytes": 50376,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/sky-full-1600.ed767ec90d.webp",
            "width": 1600,
            "height": 900,
            "bytes": 110188,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v2/places/paris-landmark/ground-full-1800.555004320c.webp",
            "width": 1800,
            "height": 108,
            "bytes": 22124,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/ground-full-3600.159e5c24ac.webp",
            "width": 3600,
            "height": 216,
            "bytes": 50336,
            "crop": "full"
          }
        ],
        "night": [
          {
            "url": "/scenes/paris/v2/places/paris-landmark/night-full-1920.140b5b35d5.webp",
            "width": 1920,
            "height": 640,
            "bytes": 208912,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/night-full-2560.ebfbb8b9c2.webp",
            "width": 2560,
            "height": 853,
            "bytes": 292188,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/night-full-3600.a36afef278.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 428772,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/night-center-800.33a0925933.webp",
            "width": 800,
            "height": 800,
            "bytes": 68036,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v2/places/paris-landmark/night-center-1200.6079f05456.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 107240,
            "crop": "center"
          }
        ]
      }
    }
  }
});
