/* Generated by pnpm scenes:build. Edit art/paris/places.json, conversations.json or pack.json, then rebuild. */
import { createPhase2CountryPack } from "./phase2-factory";

export const parisCountryPackV3 = createPhase2CountryPack({
  "packId": "paris-v3",
  "countryCode": "FR",
  "countryName": "France",
  "cityName": "Paris",
  "timeZone": "Europe/Paris",
  "lat": 48.8566,
  "lon": 2.3522,
  "neighbours": [],
  "voteBlurb": "Station boulevards, canal paths, market passages and the Seine, ending beneath the evening lights.",
  "zones": [
    {
      "id": "paris-arrival",
      "label": "Gare du Nord",
      "weather": "clear",
      "palette": [
        "#aaccee",
        "#aa9988",
        "#777777"
      ],
      "kind": "arrival",
      "tags": [
        "arrival",
        "station"
      ],
      "description": "First steps outside the station, on pale stone and a long morning pavement.",
      "stage": {
        "palette": [
          "#aaccee",
          "#aa9988",
          "#777777"
        ]
      }
    },
    {
      "id": "paris-lanes",
      "label": "Canal Saint-Martin",
      "weather": "breeze",
      "palette": [
        "#888888",
        "#ccaa99",
        "#aaccee"
      ],
      "kind": "lanes",
      "tags": [
        "lanes",
        "canal"
      ],
      "description": "A quiet canal promenade under plane trees, with an iron footbridge.",
      "stage": {
        "palette": [
          "#888888",
          "#ccaa99",
          "#aaccee"
        ]
      }
    },
    {
      "id": "paris-market",
      "label": "Marais market street",
      "weather": "haze",
      "palette": [
        "#888888",
        "#eeccaa",
        "#ccaa99"
      ],
      "kind": "market",
      "tags": [
        "market"
      ],
      "description": "Covered stalls, flowers and small doors in the Marais.",
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#ccaa99"
        ]
      }
    },
    {
      "id": "paris-cafe",
      "label": "Left Bank café",
      "weather": "golden",
      "palette": [
        "#888888",
        "#eeccaa",
        "#663333"
      ],
      "kind": "cafe",
      "tags": [
        "cafe"
      ],
      "description": "A calm corner café with empty tables on a Left Bank side street.",
      "stage": {
        "palette": [
          "#888888",
          "#eeccaa",
          "#663333"
        ]
      }
    },
    {
      "id": "paris-landmark",
      "label": "The Seine and the Eiffel Tower",
      "weather": "evening",
      "palette": [
        "#776666",
        "#8899cc",
        "#ffbb77"
      ],
      "kind": "landmark",
      "tags": [
        "landmark",
        "river",
        "eiffel-view"
      ],
      "description": "The river widens and the tower comes into view as the light softens.",
      "stage": {
        "palette": [
          "#776666",
          "#8899cc",
          "#ffbb77"
        ]
      }
    },
    {
      "id": "paris-montmartre",
      "label": "Montmartre and Sacré-Cœur",
      "weather": "clear",
      "palette": [
        "#aaccff",
        "#bbaa99",
        "#998888"
      ],
      "kind": "landmark",
      "tags": [
        "montmartre",
        "landmark",
        "steps"
      ],
      "description": "Broad Montmartre steps rise toward Sacré-Cœur above warm stone terraces.",
      "stage": {
        "palette": [
          "#aaccff",
          "#bbaa99",
          "#998888"
        ]
      }
    },
    {
      "id": "paris-vosges",
      "label": "Place des Vosges",
      "weather": "golden",
      "palette": [
        "#99ccee",
        "#bbaa99",
        "#ffddbb"
      ],
      "tags": [
        "square",
        "arcades",
        "marais",
        "vosges"
      ],
      "description": "Brick arcades and clipped trees frame the quiet paths of Place des Vosges.",
      "stage": {
        "palette": [
          "#99ccee",
          "#bbaa99",
          "#ffddbb"
        ]
      }
    },
    {
      "id": "paris-luxembourg",
      "label": "Luxembourg Garden",
      "weather": "breeze",
      "palette": [
        "#eeccaa",
        "#99ccff",
        "#998888"
      ],
      "kind": "landmark",
      "tags": [
        "garden",
        "landmark"
      ],
      "description": "The Luxembourg Garden opens behind its railings, with pale paths and green chairs.",
      "stage": {
        "palette": [
          "#eeccaa",
          "#99ccff",
          "#998888"
        ]
      }
    },
    {
      "id": "paris-alexandre",
      "label": "Pont Alexandre III",
      "weather": "golden",
      "palette": [
        "#ddbb99",
        "#887777",
        "#88bbee"
      ],
      "kind": "landmark",
      "tags": [
        "bridge",
        "river",
        "landmark"
      ],
      "description": "Pont Alexandre III crosses the Seine beneath gilded lamps and a wide Paris sky.",
      "stage": {
        "palette": [
          "#ddbb99",
          "#887777",
          "#88bbee"
        ]
      }
    },
    {
      "id": "paris-saint-germain",
      "label": "Saint-Germain bookshop street",
      "weather": "haze",
      "palette": [
        "#aa9988",
        "#eeccaa",
        "#887777"
      ],
      "kind": "lanes",
      "tags": [
        "bookshop",
        "saint-germain",
        "lanes"
      ],
      "description": "A narrow Saint-Germain street passes old bookshop windows and shaded café fronts.",
      "stage": {
        "palette": [
          "#aa9988",
          "#eeccaa",
          "#887777"
        ]
      }
    }
  ],
  "sceneVisitSeconds": 420,
  "encounter": {
    "npcId": "paris-resident",
    "locationLabel": "Canal Saint-Martin",
    "phrase": {
      "original": "Bonjour, je découvre Paris à pied.",
      "transliteration": "Bon-zhoor, zhuh day-koovr Pa-ree ah pyay.",
      "gloss": "Hello, I am discovering Paris on foot.",
      "pronunciation": "bon-ZHOOR, zhuh day-KOOVR pah-REE ah PYAY"
    },
    "exchange": [
      "Bonjour! Are you finding your way from the station?",
      "Bonjour. Yes, I am discovering Paris on foot.",
      "Follow the canal for a quieter start. The city changes pace beside the water.",
      "That sounds better than rushing straight to the famous view.",
      "There is time for the market, a café, and the river before evening.",
      "Merci, Camille. I will let the streets lead me there."
    ],
    "dialogue": [
      {
        "speaker": "npc",
        "text": "Bonjour! Are you finding your way from the station?",
        "mood": "curious"
      },
      {
        "speaker": "traveler",
        "text": "Bonjour. Yes, I am discovering Paris on foot.",
        "mood": "amused"
      },
      {
        "speaker": "npc",
        "text": "Follow the canal for a quieter start. The city changes pace beside the water.",
        "mood": "thoughtful"
      },
      {
        "speaker": "traveler",
        "text": "That sounds better than rushing straight to the famous view.",
        "mood": "thoughtful"
      },
      {
        "speaker": "npc",
        "text": "There is time for the market, a café, and the river before evening.",
        "mood": "neutral"
      },
      {
        "speaker": "traveler",
        "text": "Merci, Camille. I will let the streets lead me there.",
        "mood": "amused"
      }
    ]
  },
  "conversations": [
    {
      "id": "paris-canal-welcome",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "lanes"
      ],
      "role": "story",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Are you finding your way from the station?",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Yes, I am discovering Paris on foot.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Follow the canal for a quieter start. The city changes pace beside the water.",
          "mood": "thoughtful",
          "durationMs": 5400
        },
        {
          "speaker": "traveler",
          "text": "That sounds better than rushing straight to the famous view.",
          "mood": "thoughtful",
          "durationMs": 4300
        },
        {
          "speaker": "npc",
          "text": "There is time for the market, a café, and the river before evening.",
          "mood": "neutral",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Merci, Camille. I will let the streets lead me there.",
          "mood": "amused",
          "durationMs": 4300
        }
      ]
    },
    {
      "id": "paris-station-directions",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "arrival",
        "station"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! You look ready for a long walk.",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. I am, once I choose the right street.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Start toward the canal. The pavements become calmer after the station streets.",
          "mood": "thoughtful",
          "durationMs": 5200
        },
        {
          "speaker": "traveler",
          "text": "Perfect. A calm beginning will help me find my rhythm.",
          "mood": "amused",
          "durationMs": 4400
        }
      ]
    },
    {
      "id": "paris-canal-footbridge",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "canal"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! The canal suits your walking pace today.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. It is difficult to hurry beside this water.",
          "mood": "thoughtful",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Pause halfway across the footbridge. The view opens from the middle.",
          "mood": "curious",
          "durationMs": 5000
        },
        {
          "speaker": "traveler",
          "text": "I will. A short pause still counts as exploring.",
          "mood": "amused",
          "durationMs": 4200
        }
      ]
    },
    {
      "id": "paris-market-peaches",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "market"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Have you seen the fruit stall around the corner?",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Not yet, but I can smell something sweet.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "The peaches are good today. Look before the afternoon crowd arrives.",
          "mood": "neutral",
          "durationMs": 5000
        },
        {
          "speaker": "traveler",
          "text": "Then my timing is lucky. Merci for the tip.",
          "mood": "amused",
          "durationMs": 4000
        }
      ]
    },
    {
      "id": "paris-cafe-counter",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "cafe"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Are you stopping for coffee or only passing through?",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Coffee, if I can enjoy it without rushing.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Stand at the counter for a quick cup, or take a table when you want a longer pause.",
          "mood": "neutral",
          "durationMs": 5900
        },
        {
          "speaker": "traveler",
          "text": "A quick cup today. The street is asking me to keep walking.",
          "mood": "thoughtful",
          "durationMs": 4800
        }
      ]
    },
    {
      "id": "paris-cafe-to-river",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "cafe",
        "eiffel-view"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Did the café persuade you to stay?",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Nearly, but I still want to reach the river.",
          "mood": "thoughtful",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Keep walking toward the brighter sky between the buildings. The river will appear soon.",
          "mood": "neutral",
          "durationMs": 5600
        },
        {
          "speaker": "traveler",
          "text": "That is a direction I can remember. Merci.",
          "mood": "amused",
          "durationMs": 3900
        }
      ]
    },
    {
      "id": "paris-seine-bookstalls",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "eiffel-view"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! The river has given you a little more sky.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. I noticed that before I noticed the tower.",
          "mood": "thoughtful",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "The green bookstalls along the quay reward a slow look as well.",
          "mood": "curious",
          "durationMs": 4900
        },
        {
          "speaker": "traveler",
          "text": "Then I will divide my attention between books and the view.",
          "mood": "amused",
          "durationMs": 4500
        }
      ]
    },
    {
      "id": "paris-montmartre-steps",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "montmartre",
        "steps"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Those steps are easier if you do not race them.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. I was hoping they would reward patience.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Turn around once you are higher. Paris keeps widening behind you.",
          "mood": "thoughtful",
          "durationMs": 4900
        },
        {
          "speaker": "traveler",
          "text": "Good advice. The climb should include the view it creates.",
          "mood": "thoughtful",
          "durationMs": 4400
        }
      ]
    },
    {
      "id": "paris-vosges-arcades",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "vosges"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! You found one of the calmest corners of the square.",
          "mood": "neutral",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. The arcades make the whole place feel sheltered.",
          "mood": "thoughtful",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Walk beneath them, then come back through the garden. The two routes feel completely different.",
          "mood": "curious",
          "durationMs": 5900
        },
        {
          "speaker": "traveler",
          "text": "I like a square that offers a second version of itself.",
          "mood": "amused",
          "durationMs": 4300
        }
      ]
    },
    {
      "id": "paris-vosges-garden",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "vosges"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Have you tried the path beneath the trees?",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Not yet; I was following the red-brick arcade.",
          "mood": "neutral",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Cross the garden on your next turn. The centre feels quieter than the street outside.",
          "mood": "thoughtful",
          "durationMs": 5500
        },
        {
          "speaker": "traveler",
          "text": "I will take the quieter route before moving on.",
          "mood": "thoughtful",
          "durationMs": 4100
        }
      ]
    },
    {
      "id": "paris-luxembourg-chairs",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "garden"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! The green chairs are an invitation, you know.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. My feet understood the invitation immediately.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Choose one facing the path. Resting here is also a way of watching Paris pass.",
          "mood": "thoughtful",
          "durationMs": 5500
        },
        {
          "speaker": "traveler",
          "text": "One quiet minute, then I will join the path again.",
          "mood": "neutral",
          "durationMs": 4300
        }
      ]
    },
    {
      "id": "paris-alexandre-details",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "bridge"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! The bridge is making you look in every direction.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. There is too much detail for one glance.",
          "mood": "surprised",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Look up at the lamps, then down the river. The grand view is built from small things.",
          "mood": "thoughtful",
          "durationMs": 5600
        },
        {
          "speaker": "traveler",
          "text": "Then I will give the bridge the time it is asking for.",
          "mood": "thoughtful",
          "durationMs": 4400
        }
      ]
    },
    {
      "id": "paris-river-to-books",
      "residentType": "resident-a",
      "speakerName": "Inès",
      "placeTags": [
        "bridge",
        "bookshop"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Are you following the river or looking for the bookshops?",
          "mood": "curious",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. I was following the river, but books could change the route.",
          "mood": "amused",
          "durationMs": 5000
        },
        {
          "speaker": "npc",
          "text": "Turn into Saint-Germain when the streets narrow. The shop windows will slow you down.",
          "mood": "neutral",
          "durationMs": 5500
        },
        {
          "speaker": "traveler",
          "text": "That sounds like a worthwhile delay. Merci.",
          "mood": "amused",
          "durationMs": 3900
        }
      ]
    },
    {
      "id": "paris-saint-germain-books",
      "residentType": "resident-b",
      "speakerName": "Camille",
      "placeTags": [
        "bookshop"
      ],
      "role": "ambient",
      "review": "approved",
      "lines": [
        {
          "speaker": "npc",
          "text": "Bonjour! Did a bookshop window finally stop you?",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "traveler",
          "text": "Bonjour. Only for a moment, but it was a convincing window.",
          "mood": "amused",
          "durationMs": 4800
        },
        {
          "speaker": "npc",
          "text": "Browse without a plan. The smallest shelves often hold the best surprise.",
          "mood": "curious",
          "durationMs": 5000
        },
        {
          "speaker": "traveler",
          "text": "I can make room for one surprise before the route begins again.",
          "mood": "thoughtful",
          "durationMs": 4600
        }
      ]
    }
  ],
  "resident": {
    "name": "Camille",
    "role": "Canal-side resident",
    "variantId": "paris-resident-b"
  },
  "notebookLines": [
    "The station opened onto pale stone and a long morning pavement.",
    "Canal water made the city feel quieter without making it still.",
    "An iron footbridge held the middle of the view for a few steps.",
    "The market lane traded grand facades for flowers, produce and small doors.",
    "Lunch arrived as a pause at the edge of a Left Bank side street.",
    "The best parts of the route were the changes in scale between each district.",
    "The Seine widened the horizon just as the light began to soften.",
    "At night, the same riverside view felt newly drawn in blue and gold."
  ],
  "postcardTitle": "Evening beside the Seine",
  "postcardCopy": "Ten Paris places later, the river opened and the tower caught the last light.",
  "sourceNotes": [
    "Scene manifest v3 for Paris: 10 places; owner/creator review is recorded.",
    "AI-assisted source paintings are preserved under art/paris; the build derives content-addressed renditions and makes no cultural claims."
  ],
  "culturalReview": {
    "reviewerName": "Shokhrukh Karimov",
    "reviewedAt": "2026-09-13T00:00:00.000Z",
    "status": "creator_reviewed",
    "qualification": "Owner visual and dialogue review for this Paris journey candidate",
    "disposition": "Approved by the owner for the Paris v3 journey candidate",
    "publicLaunchRequirement": "Qualified local review remains required before public launch.",
    "citations": [],
    "notes": "Owner approved the ten paintings and Day 1 conversations on 13 September 2026."
  },
  "assetBudgetBytes": 5767168,
  "authoredAssets": {
    "variants": {
      "paris-arrival": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-arrival/city-full-1920.fe745ffe8d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 242670,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/city-full-2560.f369ba3fd8.webp",
            "width": 2560,
            "height": 853,
            "bytes": 341488,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/city-full-3600.609a458a53.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 506652,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/city-center-800.1b08210e6b.webp",
            "width": 800,
            "height": 800,
            "bytes": 79194,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/city-center-1200.c482f39da5.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 124290,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-arrival/sky-full-800.6ac25de359.webp",
            "width": 800,
            "height": 450,
            "bytes": 42760,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/sky-full-1600.53c0a6baa7.webp",
            "width": 1600,
            "height": 900,
            "bytes": 93618,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-arrival/ground-full-1800.e6aab87308.webp",
            "width": 1800,
            "height": 108,
            "bytes": 18382,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-arrival/ground-full-3600.c17dc5c232.webp",
            "width": 3600,
            "height": 216,
            "bytes": 42084,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-lanes": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-lanes/city-full-1920.0112f7c653.webp",
            "width": 1920,
            "height": 640,
            "bytes": 287166,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/city-full-2560.6e4f2f6580.webp",
            "width": 2560,
            "height": 853,
            "bytes": 399690,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/city-full-3600.c5ba29a782.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 580176,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/city-center-800.9429832f5e.webp",
            "width": 800,
            "height": 800,
            "bytes": 111486,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/city-center-1200.eb178309d3.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 174052,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-lanes/sky-full-800.29c28f1089.webp",
            "width": 800,
            "height": 450,
            "bytes": 57580,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/sky-full-1600.6c5740fae6.webp",
            "width": 1600,
            "height": 900,
            "bytes": 125314,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-lanes/ground-full-1800.1eb210d23d.webp",
            "width": 1800,
            "height": 108,
            "bytes": 17786,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-lanes/ground-full-3600.b27c1833f4.webp",
            "width": 3600,
            "height": 216,
            "bytes": 40000,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-market": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-market/city-full-1920.27276a734d.webp",
            "width": 1920,
            "height": 640,
            "bytes": 290890,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/city-full-2560.16c4ca7e41.webp",
            "width": 2560,
            "height": 853,
            "bytes": 416726,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/city-full-3600.8909e99a60.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 604960,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/city-center-800.b98dede687.webp",
            "width": 800,
            "height": 800,
            "bytes": 127542,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/city-center-1200.15c0aef7f1.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 201712,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-market/sky-full-800.8eef0ba4d1.webp",
            "width": 800,
            "height": 450,
            "bytes": 60450,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/sky-full-1600.5480b242c4.webp",
            "width": 1600,
            "height": 900,
            "bytes": 127356,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-market/ground-full-1800.20197c79d0.webp",
            "width": 1800,
            "height": 108,
            "bytes": 19458,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-market/ground-full-3600.f83820bd71.webp",
            "width": 3600,
            "height": 216,
            "bytes": 44836,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-cafe": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-cafe/city-full-1920.68ce8e0949.webp",
            "width": 1920,
            "height": 640,
            "bytes": 295342,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/city-full-2560.b769c0290a.webp",
            "width": 2560,
            "height": 853,
            "bytes": 412050,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/city-full-3600.cc6b2b4101.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 609418,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/city-center-800.52cdf0641d.webp",
            "width": 800,
            "height": 800,
            "bytes": 104930,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/city-center-1200.a1c15a5d01.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 163394,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-cafe/sky-full-800.8983ff8aa5.webp",
            "width": 800,
            "height": 450,
            "bytes": 61752,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/sky-full-1600.e8df8a8779.webp",
            "width": 1600,
            "height": 900,
            "bytes": 129976,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-cafe/ground-full-1800.e968719bb5.webp",
            "width": 1800,
            "height": 108,
            "bytes": 22120,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-cafe/ground-full-3600.01bb792370.webp",
            "width": 3600,
            "height": 216,
            "bytes": 49596,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-landmark": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-landmark/city-full-1920.374e149d23.webp",
            "width": 1920,
            "height": 640,
            "bytes": 250962,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/city-full-2560.12d0682b43.webp",
            "width": 2560,
            "height": 853,
            "bytes": 349196,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/city-full-3600.1b5d0ad2b0.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 511890,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/city-center-800.4806bb150a.webp",
            "width": 800,
            "height": 800,
            "bytes": 80118,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/city-center-1200.ffeef9750e.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 127282,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-landmark/sky-full-800.6aabb7ee79.webp",
            "width": 800,
            "height": 450,
            "bytes": 50376,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/sky-full-1600.ed767ec90d.webp",
            "width": 1600,
            "height": 900,
            "bytes": 110188,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-landmark/ground-full-1800.555004320c.webp",
            "width": 1800,
            "height": 108,
            "bytes": 22124,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/ground-full-3600.159e5c24ac.webp",
            "width": 3600,
            "height": 216,
            "bytes": 50336,
            "crop": "full"
          }
        ],
        "night": [
          {
            "url": "/scenes/paris/v3/places/paris-landmark/night-full-1920.140b5b35d5.webp",
            "width": 1920,
            "height": 640,
            "bytes": 208912,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/night-full-2560.ebfbb8b9c2.webp",
            "width": 2560,
            "height": 853,
            "bytes": 292188,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/night-full-3600.a36afef278.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 428772,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/night-center-800.33a0925933.webp",
            "width": 800,
            "height": 800,
            "bytes": 68036,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-landmark/night-center-1200.6079f05456.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 107240,
            "crop": "center"
          }
        ]
      },
      "paris-montmartre": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/city-full-1920.12b64c17d6.webp",
            "width": 1920,
            "height": 640,
            "bytes": 295864,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/city-full-2560.aaeea77765.webp",
            "width": 2560,
            "height": 853,
            "bytes": 417856,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/city-full-3600.fd8a9addb4.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 610860,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/city-center-800.c50b8dfea0.webp",
            "width": 800,
            "height": 800,
            "bytes": 130910,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/city-center-1200.b91c5a537c.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 207876,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/sky-full-800.5291fee9d7.webp",
            "width": 800,
            "height": 450,
            "bytes": 57090,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/sky-full-1600.28ec6e8805.webp",
            "width": 1600,
            "height": 900,
            "bytes": 122244,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/ground-full-1800.5e76dbcd26.webp",
            "width": 1800,
            "height": 108,
            "bytes": 31592,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-montmartre/ground-full-3600.1ec2a53751.webp",
            "width": 3600,
            "height": 216,
            "bytes": 70290,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-vosges": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-vosges/city-full-1920.3c72b82636.webp",
            "width": 1920,
            "height": 640,
            "bytes": 312030,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/city-full-2560.0cd537bf8c.webp",
            "width": 2560,
            "height": 853,
            "bytes": 441972,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/city-full-3600.142eeddab8.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 648208,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/city-center-800.bf07bac054.webp",
            "width": 800,
            "height": 800,
            "bytes": 108722,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/city-center-1200.b28494f0b2.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 172494,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-vosges/sky-full-800.dfdca8abe4.webp",
            "width": 800,
            "height": 450,
            "bytes": 55424,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/sky-full-1600.ac358fcfd4.webp",
            "width": 1600,
            "height": 900,
            "bytes": 118804,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-vosges/ground-full-1800.362ef81ea8.webp",
            "width": 1800,
            "height": 108,
            "bytes": 38982,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-vosges/ground-full-3600.865cbf6aa9.webp",
            "width": 3600,
            "height": 216,
            "bytes": 89220,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-luxembourg": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/city-full-1920.d5aea61d5b.webp",
            "width": 1920,
            "height": 640,
            "bytes": 248284,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/city-full-2560.e232b26c1f.webp",
            "width": 2560,
            "height": 853,
            "bytes": 351588,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/city-full-3600.44a32d2e49.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 519526,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/city-center-800.20fdce5a2f.webp",
            "width": 800,
            "height": 800,
            "bytes": 98776,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/city-center-1200.a718055f62.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 156670,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/sky-full-800.c43b2b84d9.webp",
            "width": 800,
            "height": 450,
            "bytes": 48160,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/sky-full-1600.ac6fdeb6de.webp",
            "width": 1600,
            "height": 900,
            "bytes": 103304,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/ground-full-1800.8e49096de2.webp",
            "width": 1800,
            "height": 108,
            "bytes": 30824,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-luxembourg/ground-full-3600.2699ee639f.webp",
            "width": 3600,
            "height": 216,
            "bytes": 75004,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-alexandre": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/city-full-1920.10d44ba10e.webp",
            "width": 1920,
            "height": 640,
            "bytes": 241240,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/city-full-2560.72a7c0e089.webp",
            "width": 2560,
            "height": 853,
            "bytes": 337076,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/city-full-3600.a3b998eea5.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 492334,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/city-center-800.11fa5e6983.webp",
            "width": 800,
            "height": 800,
            "bytes": 99224,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/city-center-1200.0b01cbcb54.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 157470,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/sky-full-800.2233edecdf.webp",
            "width": 800,
            "height": 450,
            "bytes": 50466,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/sky-full-1600.dd2b265dba.webp",
            "width": 1600,
            "height": 900,
            "bytes": 106698,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/ground-full-1800.7bd491f6ea.webp",
            "width": 1800,
            "height": 108,
            "bytes": 25028,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-alexandre/ground-full-3600.6643fa429c.webp",
            "width": 3600,
            "height": 216,
            "bytes": 55380,
            "crop": "full"
          }
        ],
        "night": []
      },
      "paris-saint-germain": {
        "nominalWidth": 3600,
        "nominalHeight": 1200,
        "city": [
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/city-full-1920.3059942bf5.webp",
            "width": 1920,
            "height": 640,
            "bytes": 290060,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/city-full-2560.0d776c6ea3.webp",
            "width": 2560,
            "height": 853,
            "bytes": 404506,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/city-full-3600.c3b413c66c.webp",
            "width": 3600,
            "height": 1200,
            "bytes": 599622,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/city-center-800.ed07f2d687.webp",
            "width": 800,
            "height": 800,
            "bytes": 135878,
            "crop": "center"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/city-center-1200.f57676b369.webp",
            "width": 1200,
            "height": 1200,
            "bytes": 214942,
            "crop": "center"
          }
        ],
        "sky": [
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/sky-full-800.13c501b2c9.webp",
            "width": 800,
            "height": 450,
            "bytes": 65374,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/sky-full-1600.b10a40e44a.webp",
            "width": 1600,
            "height": 900,
            "bytes": 140596,
            "crop": "full"
          }
        ],
        "ground": [
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/ground-full-1800.50a146115f.webp",
            "width": 1800,
            "height": 108,
            "bytes": 21322,
            "crop": "full"
          },
          {
            "url": "/scenes/paris/v3/places/paris-saint-germain/ground-full-3600.d43584e2c7.webp",
            "width": 3600,
            "height": 216,
            "bytes": 48156,
            "crop": "full"
          }
        ],
        "night": []
      }
    }
  }
});
