-- P20: private local corrections, moderation and distinct accepted contributors.

create type public.correction_category as enum ('place', 'phrase', 'dialogue', 'art', 'other');
create type public.correction_status as enum ('new', 'accepted', 'rejected');

create table public.corrections (
  id bigint generated by default as identity primary key,
  pack_id text not null check (pack_id ~ '^[a-z0-9]+(-[a-z0-9]+)*-v[0-9]+$'),
  zone_id text check (zone_id is null or zone_id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  category public.correction_category not null,
  body text not null check (char_length(btrim(body)) between 1 and 280),
  visitor_hash text not null check (length(visitor_hash) = 64),
  country_code char(2) not null default 'ZZ' check (country_code ~ '^[A-Z]{2}$'),
  status public.correction_status not null default 'new',
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  check (status = 'new' or reviewed_at is not null)
);

create index corrections_queue_idx on public.corrections (status, created_at, id);
create index corrections_pack_accepted_idx
  on public.corrections (pack_id, visitor_hash) where status = 'accepted';

alter table public.corrections enable row level security;
revoke all on public.corrections from public, anon, authenticated;

create or replace function public.submit_correction(
  p_visitor_hash text,
  p_pack_id text,
  p_zone_id text,
  p_category public.correction_category,
  p_body text,
  p_country_code text,
  p_now timestamptz
)
returns table (out_id bigint, out_rate_limited boolean)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
  v_allowed boolean;
begin
  if p_visitor_hash is null or length(p_visitor_hash) <> 64 then
    raise exception 'invalid visitor hash' using errcode = '22023';
  end if;
  if p_pack_id is null or p_pack_id !~ '^[a-z0-9]+(-[a-z0-9]+)*-v[0-9]+$' then
    raise exception 'invalid pack id' using errcode = '22023';
  end if;
  if p_zone_id is not null and p_zone_id !~ '^[a-z0-9]+(-[a-z0-9]+)*$' then
    raise exception 'invalid zone id' using errcode = '22023';
  end if;
  if p_body is null or char_length(btrim(p_body)) not between 1 and 280 then
    raise exception 'invalid correction body' using errcode = '22023';
  end if;

  v_allowed := public.consume_mutation_rate_limit(
    p_visitor_hash, 'correction', 3, 3600, p_now
  );
  if not v_allowed then
    return query select null::bigint, true;
    return;
  end if;

  insert into public.corrections (
    pack_id, zone_id, category, body, visitor_hash, country_code, created_at
  ) values (
    p_pack_id, nullif(p_zone_id, ''), p_category, btrim(p_body), p_visitor_hash,
    public.normalize_country_code(p_country_code)::char(2), p_now
  ) returning id into v_id;

  return query select v_id, false;
end;
$$;

create or replace function public.moderate_correction(
  p_id bigint,
  p_status public.correction_status,
  p_now timestamptz
)
returns table (out_id bigint, out_status public.correction_status, out_pack_id text, out_contributors bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_correction public.corrections%rowtype;
begin
  if p_status not in ('accepted', 'rejected') then
    raise exception 'invalid moderation status' using errcode = '22023';
  end if;
  select c.* into v_correction from public.corrections c where c.id = p_id for update;
  if not found then
    raise exception 'correction not found' using errcode = 'P0002';
  end if;

  if v_correction.status is distinct from p_status then
    update public.corrections c set status = p_status, reviewed_at = p_now where c.id = p_id;
  end if;

  return query select
    v_correction.id,
    p_status,
    v_correction.pack_id,
    (select count(distinct c.visitor_hash) from public.corrections c
      where c.pack_id = v_correction.pack_id and c.status = 'accepted');
end;
$$;

create or replace function public.read_pack_correction_contributors(p_pack_id text)
returns bigint
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select count(distinct c.visitor_hash)
  from public.corrections c
  where c.pack_id = p_pack_id and c.status = 'accepted';
$$;

revoke all on function public.submit_correction(text, text, text, public.correction_category, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.moderate_correction(bigint, public.correction_status, timestamptz) from public, anon, authenticated;
revoke all on function public.read_pack_correction_contributors(text) from public, anon, authenticated;
grant execute on function public.submit_correction(text, text, text, public.correction_category, text, text, timestamptz) to service_role;
grant execute on function public.moderate_correction(bigint, public.correction_status, timestamptz) to service_role;
grant execute on function public.read_pack_correction_contributors(text) to service_role;
